// Copyright 2019 Nina Marie Wahl og Charlotte Heggem.
// Copyright 2019 Norwegian University of Science and Technology.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package API_ROS2_Sunrise;


import javax.inject.Inject;
import java.util.concurrent.TimeUnit;

import com.kuka.roboticsAPI.annotations.AutomaticResumeManager;
import com.kuka.roboticsAPI.annotations.IAutomaticResumeFunction;
import com.kuka.roboticsAPI.applicationModel.tasks.CycleBehavior;
import com.kuka.roboticsAPI.applicationModel.tasks.RoboticsAPICyclicBackgroundTask;
import com.kuka.task.properties.TaskFunctionProvider;

/**
 * DO NOT EDIT THIS FILE!
 * DO NOT EDIT THIS FILE!
 * DO NOT EDIT THIS FILE!
 */
public class AutomaticResumeBackgroundTask extends RoboticsAPICyclicBackgroundTask {
	@Inject
	private AutomaticResumeManager _automaticResumeManager;

	@Override
	public void initialize() {
		initializeCyclic(0, 500, TimeUnit.MILLISECONDS,
				CycleBehavior.BestEffort);
	}

	@Override
	public void runCyclic() {
	}
	
	@TaskFunctionProvider
	public IAutomaticResumeFunction getAutomaticResumeFunction() {
		return _automaticResumeManager;
	}
}
